apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: RH1-Demo-Template
  title: Bontreger - RH1 Demo
  description: Create a preconfigured Git project with some scaffolds.
  tags:
    - recommended
    - ansible
    - playbook
spec:
  owner: user:default/bontreger
  system: ansible
  type: service
  parameters:
    - title: Provide information about the new component
      required:
        - repoOwner
        - repoName
        - owner
        - collectionGroup
        - collectionName
      properties:
        sourceControl:
          title: Select source control option
          type: string
          description: Select the source control option for your Ansible project.
          default: github.com
          enum:
            - github.com
          enumNames:
            - 'GitHub'
        repoOwner:
          title: Source code repository organization name or username
          type: string
          description: The organization name or username of your source code repository. For example, “my-github-username”.
          maxLength: 100
        repoName:
          title: Playbook repository name
          description: The name of the new playbook project repository. For example, “my-new-playbook-repo”.
          type: string
          maxLength: 100
          pattern: '^([a-zA-Z][a-zA-Z0-9_]*)(-[a-zA-Z0-9_]+)*$'
        description:
          title: Playbook description
          type: string
          description: Describe the playbook and its purpose to help other users understand what to use it for.
          maxLength: 350
        collectionGroup:
          title: Playbook project's collection namespace
          description: The collection namespace in your new playbook repository. For example, “my_new_collection_namespace”.
          type: string
          maxLength: 63
          minLength: 2
          pattern: '^[a-z][a-z0-9_]+$'
        collectionName:
          title: Playbook project's collection name
          description: The collection name in your new playbook repository. For example, “my_new_collection_name”.
          type: string
          maxLength: 63
          minLength: 2
          pattern: '^[a-z][a-z0-9_]+$'
        owner:
          title: Catalog Owner name
          type: string
          description: The Red Hat Developer Hub catalog item owner. This will appear on the “My items” tab. For example, “my-devhub-username”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          description: The Red Hat Developer Hub system catalog item name. This will appear on the “My items” tab. For example, “my-devhub-system”.
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
steps:
    # 1. CREATE THE ANSIBLE PROJECT
    # Output: Creates a folder named "${{ parameters.repoName }}" in the workspace
    - id: ansible
      name: Generating the Ansible Source Code Component
      action: ansible:content:create
      input:
        repoOwner: '${{ parameters.repoOwner }}'
        repoName: '${{ parameters.repoName }}'
        description: '${{ parameters.description }}'
        collectionGroup: '${{ parameters.collectionGroup }}'
        collectionName: '${{ parameters.collectionName }}'
        applicationType: playbook-project
        sourceControl: '${{ parameters.sourceControl }}'

    # 2. GENERATE DATE (For your README)
    - id: get_date
      name: Generate Timestamp
      action: roadiehq:utils:jsonata
      input:
        expression: $fromMillis($millis(), '[Y0001]-[M01]-[D01]')

    # 3. DOWNLOAD SKELETON (Into the Ansible folder)
    # We use fetch:plain because we know it works for your network.
    - id: fetch_skeleton
      name: Inject Custom Skeleton
      action: fetch:plain
      input:
        # Use the URL that we confirmed works
        url: https://github.com/bontreger-labs/ansible-rhdh-templates/tree/main/skeleton
        # CRITICAL: Put files INSIDE the folder Ansible created
        targetPath: ./${{ parameters.repoName }}

    # 4. APPLY VARIABLES (To the files we just downloaded)
    - id: template_skeleton
      name: Customize Skeleton Files
      action: fetch:template
      input:
        # Target the same folder where we just put the files
        url: ./${{ parameters.repoName }}
        targetPath: ./${{ parameters.repoName }}
        conflictStrategy: override
        values:
          # Map your specific parameters to the variables used in README.md
          name: ${{ parameters.repoName }}
          owner: ${{ parameters.repoOwner }}
          description: ${{ parameters.description }}
          run_date: ${{ steps.get_date.output.result }}

    # 5. GENERATE CATALOG INFO (Into the Ansible folder)
    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ./catalog-info/
        # CRITICAL: Put this inside the folder too
        targetPath: ./${{ parameters.repoName }}
        values:
          repoUrl: ${{ steps.ansible.output.repoUrl }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: playbook-project
          description: ${{ parameters.description }}
          collectionGroup: ${{ parameters.collectionGroup }}
          collectionName: ${{ parameters.collectionName }}
          sourceControl: ${{ parameters.sourceControl }}
          devSpacesBaseUrl: ${{ steps.ansible.output.devSpacesBaseUrl }}

    # 6. PUBLISH TO GITHUB
    - id: publish
      name: Publish
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ steps.ansible.output.repoUrl }}
        repoVisibility: 'public'
        defaultBranch: main
        # CRITICAL: Only publish the contents of the project folder
        # This makes "my-demo" the root of your new Git repo.
        sourcePath: ./${{ parameters.repoName }}

    # 7. REGISTER IN CATALOG
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
